### ISSUE TITLE
Crashes on a doc comment with module line and no definitions

### ISSUE THREAD

**Issue by Janiczek** [avh4/elm-format#595] opened 2019-02-10 16:43 UTC
```elm
module SSCCE exposing (foo)


{-|

    module Foo exposing (..)

-}
foo : ()
foo = ()
```

elm-format 0.8.1 crashes with
```
Processing file SSCCE.elm
elm-format: stack1: empty structure
CallStack (from HasCallStack):
  error, called at src/Box.hs:118:13 in elm-format-0.8.1-GpDgNNcXCT0J1PqNMKmSNt:Box
```

**Comment by avh4** [comment] 2019-07-28 01:49
This is occurring because of a slightly different root cause bug: module lines are always getting stripped from valid elm code blocks.

**Comment by avh4** [comment] 2019-07-28 02:49
Thanks for finding this!  This should be fixed in https://github.com/avh4/elm-format/pull/621

**Closed by avh4** 2019-07-28 02:49 UTC
Labels: bug
