### ISSUE TITLE
Single-line/multiline duality in function application

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#148] opened 2016-03-23 16:25 UTC
Here is some Elm code that is natural to write:

```elm
view model  =
  div [ class "content" ]
    [ h1 [] [ text "My Application" ]
    , div [ id "images" ]
        [ img [ src "..." ] []
        , img [ src "..." ] []
        , img [ src "..." ] []
        ]
    ]
```

`elm-format` does not allow this, because the first argument to `div` goes on the first line but the second argument to `div` is on the following line. Instead it will rearrange the above to this:

```elm
view model =
  div
    [ class "content" ]
    [ h1 [] [ text "My Application" ]
    , div
        [ id "images" ]
        [ img [ src "..." ] []
        , img [ src "..." ] []
        , img [ src "..." ] []
        ]
    ]
```

The workaround is to add parentheses:

```elm
view model  =
  (div [ class "content" ])
    [ h1 [] [ text "My Application" ]
    , (div [ id "images" ])
        [ img [ src "..." ] []
        , img [ src "..." ] []
        , img [ src "..." ] []
        ]
    ]
```

The README of [elm-css](https://github.com/rtfeldman/elm-css) also shows code that is not quite possible with elm-format, chiefly because of this same issue. For styles like `(#) Page` and `(.) NavBar`, you need to wrap them in parentheses (e.g. `, ((#) Page)` and `, ((.) NavBar)`) to get them to stay on the same line.

I am in general a big fan of elm-format reducing choice, but it's a red flag to me that neither of the choices here are styles people choose independently. I see code like the first example above all the time in the wild (as in, the non-elm-format wild), but I can only ever recall seeing the other two examples in code that's been run through elm-format.

As I recall, this is nontrivial to implement, but it seems worth discussing. It's a personal pain point, but I suspect I'm not the only one who's felt it.

Thoughts?

**Comment by avh4** [comment] 2016-03-23 16:39
Duplicate of #115

**Closed by avh4** 2016-03-23 16:39 UTC
Labels: duplicate

**Comment by rtfeldman** [comment] 2016-03-23 16:42
how did I not remember that? :dizzy_face: sorry for the dupe!
