### ISSUE TITLE
Sometimes exports get duplicated.

### ISSUE THREAD

**Issue by rupertlssmith** [avh4/elm-format#539] opened 2018-08-30 10:23 UTC
elm-format now re-arranges the exports list. I have an example with a large export list, and it seems that it ends up duplicating them.

Here is the example:

https://github.com/elm-community/typed-svg/blob/elm-format-too-many-exports/src/TypedSvg/Attributes.elm

If you delete the last 2 lines of the exports from this (which are all duplicates created by elm-format), and re-run elm-format it puts them back.

**Comment by rupertlssmith** [comment] 2018-08-30 10:27
This could be a my-bad, I have duplicates in the @docs tags too. Perhaps this is what the exports list is driven off, and just needs to be corrected there?

**Comment by avh4** [comment] 2018-08-30 15:05
Yep, you've correctly identified the issue and the workaround.  This will be fixed in 0.8.1.

**Comment by avh4** [comment] 2018-08-30 15:05
Duplicate of https://github.com/avh4/elm-format/issues/527

**Closed** 2018-09-04 23:54 UTC
Labels: bug, duplicate
