### ISSUE TITLE
Comments cause the value in record to go line below

### ISSUE THREAD

**Issue by amitaibu** [avh4/elm-format#133] opened 2016-02-04 10:58 UTC
![elm-format_all_elm_files_by_amitaibu_ _pull_request__128_ _gizra_elm-hedley](https://cloud.githubusercontent.com/assets/125707/12813158/e4c82ff0-cb3e-11e5-9f51-153987f29553.jpg)

(from [here](https://github.com/Gizra/elm-hedley/pull/128/files#diff-
2702bc537bdb3628ee779a76f3480796R32))

**Comment by avh4** [comment] 2016-02-07 03:52
Can you clarify what part of the code that comment refers to?  If it's meant to go with `nextPage`, then would the following be reasonable?

```elm
type alias Model =
  { login : Login.Model
  , -- If the user is anonymous, we want to know where to redirect them.
    nextPage : Maybe Page
  }
```

**Comment by amitaibu** [comment] 2016-02-07 09:00
> Can you clarify what part of the code that comment refers to?

It refers to the line below it (`nextPage`).

> then would the following be reasonable?

It's looks slightly weird, and not consistent - I'd expect the leading comma before the actual key. 
My expectations would be to keep it as is, but of course, I guess it's easier said than done ;)

(p.s. many thanks for this lib - it's awesome!)

**Comment by Janiczek** [comment] 2016-02-16 09:01
Related:

```elm
type Unit
    -- metric
  = Cm Float
  | Mm Float
  | M Float
    -- imperial
  | In Float
  | Ft Float
```
results in 
```elm
type
  Unit
  -- metric
  = Cm Float
  | Mm Float
  | M Float
    -- imperial
  | In Float
  | Ft Float
```

(To be fair, I don't know what's the right thing to do here. Particularly where to put the first comment in the first code snippet.)

**Comment by amitaibu** [comment] 2016-02-16 10:02
I think the "proper" way should be:

```elm
type Unit
  -- metric
  = Cm Float
  | Mm Float
  | M Float
  -- imperial
  | In Float
  | Ft Float
```

**Comment by avh4** [comment] 2017-03-09 17:37
This is now a duplicate of https://github.com/avh4/elm-format/issues/162

**Comment by avh4** [comment] 2017-03-19 22:15
The original issue about records has been fixed.

The example about `type Unit` seems contrived, and should be a separate issue if it's still a concern.

**Closed by avh4** 2017-03-19 22:15 UTC
Labels: discussion, duplicate
