### ISSUE TITLE
Records format broken when there is a comment in the middle

### ISSUE THREAD

**Issue by DavidHernandez** [avh4/elm-format#257] opened 2016-10-27 15:44 UTC
Comes from https://github.com/avh4/elm-format/issues/251

I have a complex record and I want to document it. This is how I expected it to look:

```
type alias CustomRecord =
     -- Comment
    { field : String
    , field2 : String
    -- Comment
    , field3 : String
    , field4 : String
  }
```

And this is how it looks:

```
type alias CustomRecord =
     -- Comment
    { field : String
    , field2 :
        String
        -- Comment
    , field3 : String
    , field4 : String
  }
```

**Comment by avh4** [comment] 2016-11-01 04:48
(This is similar to https://github.com/avh4/elm-format/issues/133)

**Comment by avh4** [comment] 2017-03-09 17:37
This is now a duplicate of https://github.com/avh4/elm-format/issues/162

**Comment by avh4** [comment] 2017-03-19 22:19
Fixed for elm-format 0.6.0-alpha

**Closed by avh4** 2017-03-19 22:19 UTC
Labels: duplicate
