### ISSUE TITLE
Non-idempotent URL formatting

### ISSUE THREAD

**Issue by rtfeldman** [avh4/elm-format#536] opened 2018-08-29 19:17 UTC
This is on `elm-format-0.19 0.8.0`

## SSCCE

```elm
module Foo exposing (foo)

{-| An SSCCE

[https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media\_features](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media_features)

-}


foo : Int
foo =
    5
```

Running `elm-format` on this "double wraps" the URL from this:

`[https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media\_features](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media_features)`

...to this:

`[[https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media\_features](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media_features)](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media_features)`

The outputted file looks like this:

```elm
module Foo exposing (foo)

{-| An SSCCE

[[https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media\_features](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media_features)](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Media_features)

-}


foo : Int
foo =
    5
```

Running it again doubles *that*...and so forth.

**Comment by avh4** [comment] 2018-08-29 19:32
duplicate of https://github.com/avh4/elm-format/issues/535

**Comment by avh4** [comment] 2018-08-29 20:33
(and thanks for the detailed report!)

**Comment by avh4** [comment] 2018-08-29 20:36
A possible workaround might be to replace `_` in the url with `%5F`, though I'm not familiar enough with the URL/HTTP spec to know if that's actually valid to do,  but the thing triggering this bug is the underscore in the URL, which is incorrectly being markdown escaped due to some recent code that fixes a different bug.

**Comment by avh4** [comment] 2018-08-30 02:12
Fixed in https://github.com/avh4/elm-format/pull/537

**Closed** 2018-08-30 02:42 UTC
Labels: bug, duplicate
