### ISSUE TITLE
\xADf should not format to \x0ADF

### ISSUE THREAD

**Issue by ahstro** [avh4/elm-format#462] opened 2018-02-22 11:36 UTC
Inserting a [soft hyphen](https://en.wikipedia.org/wiki/Soft_hyphen) using `\xAD` in front of the letter `f` will format format it to `\x0ADF`, e.g., `"\xADfoobar"` would turn into `"\x0ADFoobar"`, effectively inserting a new unicode character and dropping the `f` from whatever word was used.

**Comment by avh4** [comment] 2018-04-11 06:25
Duplicate of #412

**Comment by avh4** [comment] 2018-05-20 03:57
Elm 0.19 will escape characters different, so the code will now be `"\u{00AD}foobar"`, which will no longer be parsed incorrectly when formatted.

A workaround for Elm 0.18 and earlier is to change the code to `"\xAD" + "foobar"`, which will format correctly.

**Comment by avh4** [comment] 2018-06-03 02:51
This is fixed in master for Elm 0.19.  This isn't going to be fixed for Elm 0.18 and earlier, as it's an invasive fix and isn't necessary in Elm 0.19 and beyond.  (For Elm 0.18 and earlier, see the workaround mentioned here: https://github.com/avh4/elm-format/issues/462#issuecomment-390455947)

**Closed by avh4** 2018-06-03 02:51 UTC
Labels: bug, duplicate
